# permissions for end users to edit cloudsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudsecret-editor-role
rules:
- apiGroups:
  - secrets.masonwr.dev
  resources:
  - cloudsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.masonwr.dev
  resources:
  - cloudsecrets/status
  verbs:
  - get
