# permissions for end users to view cloudsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudsecret-viewer-role
rules:
- apiGroups:
  - secrets.masonwr.dev
  resources:
  - cloudsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.masonwr.dev
  resources:
  - cloudsecrets/status
  verbs:
  - get
